### ISSUE TITLE
error: non-static data member initializers

### ISSUE THREAD

**Issue by CavalhoZucchi** [setu4993/NS-3_MANET_Projects#1]
Hello, 

I just tried to build the project 3 and I get a several of the same error:

../scratch/project_3/compare.cc:43:20: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
   double txrange = 50;
                    ^
../scratch/project_3/compare.cc:44:23: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
   uint32_t interval = 10;
                       ^
../scratch/project_3/compare.cc:45:21: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
   string topology = "scratch/manet100.csv";

Can u help me?? 
Thanks

**Comment by setu4993** [comment]
Hi,

The error is because of the C++ compiler version, and not an error with the code. Update your compiler to support C++11, and the errors should go away.

Thanks.
