### ISSUE TITLE
GPSR standalone performance.

### ISSUE THREAD

**Issue by AdityaSissodiya** [setu4993/NS-3_MANET_Projects#2]
You have brilliantly enhanced GPSR with a bird flocking inspired algorithm, I was curios how the GPSR protocol would compare to it's enhanced version. Is there a way I can modify your GPSR-Bird-Flocking cases, to remove the bird flock enhancement and see just normal GPSR protocol run on the topologies  ?

**Comment by setu4993** [comment]
The GPSR model we used for comparison was from http://www.mehic.info/2016/04/greedy-perimeter-stateless-routing-gpsr-in-ns3-25/ . I would suggest using that to get the plain GPSR results.
